### ISSUE TITLE
Print all the parts of the tower

### ISSUE THREAD

**Issue by DefProc** [DoESLiverpool/st-johns-beacon#1]
- [x] Advertising Hoarding (silver)
  - [ ] Two replacement bars OR,
  - [ ] Print again.
- [x] Chimney (white)
  - This is a little spotty in quality and would be better at a lower speed.
- [x] Roof (white)
- [x] Upper Windows (Transparent Blue)
- [x] Letter Blocks (Smoked Black)
- [x] Lower Windows (Transparent Blue)
- [x] Cornice Floor (White)
- [x] Tower Base 3 (White)
- [x] Tower Base 2 (White)
- [x] Tower Base 1 (White)

**Comment by SayBeano** [comment]
I can print the chimney as it will fit on my 3D printer and I have white ABS filament.

The other pieces that will fit are the advertising hoard and the letter blocks however, don't have the colours to match.

An alternative would be that I could print the whole hoard again but in black.

**Comment by DefProc** [comment]
We have filament in 2.85mm PLA in the four colours. Will that fit your 
printer?

**Comment by SayBeano** [comment]
Right now I've no idea! It's a CEL Robox- it can take third party filament, if I print a spool housing. I'll check it out and get back to you. But do you have spare transparent or smoke rolls for me to use over the weekend?

**Comment by DefProc** [comment]
Ah, the specs say 1.75mm. Yes, it can take other filaments, but we only have 2.85mm PLA in these colours for the Ultimaker. 

The long print time means having to be in DoES to change prints across the weekend though.

**Comment by SayBeano** [comment]
OK, thanks for looking it up- I'll at least do the chimney in white- I'll recheck the stock of filaments and make sure we can't do the hoarding in grey instead of smoke. Will get back to you tomorrow.

I could access does and set a print or two off if needed.

**Comment by DefProc** [comment]
Cool, although if we're reprinting to chimney, it could do with a small hole in the top #2 

Actually, it might do better with the "roof" as an insert in the chimney…

**Comment by SayBeano** [comment]
I'm in a conference today- if there's a heads up when the model is ready I'll get it printed.

**Comment by SayBeano** [comment]
Nope not got any grey- let me know if you don't mind the hoarding in black though.

**Comment by SayBeano** [comment]
Looking at your model, on saturday with @amcewen we agreed it might look odd- the abs I have will be a different shade of white and will look a tad strange.

But I could still do the hoarding in black if you like, @DefProc?

**Comment by DefProc** [comment]
The advertising hoarding is being reprinted (as there's time) 

The chimney and tower base parts could do with a reprint in the future, but it's good enough for a first outing.
