### ISSUE TITLE
Fit an aerial to the tower using Ed's FM transmitter

### ISSUE THREAD

**Issue by cheapjack** [DoESLiverpool/st-johns-beacon#2]
Add short range FM broadcasting facilty to the tower. To broadcast NERF noise and more... Use @cheapjack cardboard analogue radio for display

**Comment by DefProc** [comment]
@amcewen suggested we could broadcast podcasts (maybe from @MesthodDan) as Radio
MakeFest.

**Comment by amcewen** [comment]
I've pinged @MethodDan to see if he's up for it.  He's running podcasting courses all day at MakeFest, so I'm hoping that they'd end up collecting a bunch of mp3s or similar, which would be added to an SD card or similar (scp-ed over to a Raspberry Pi, so it'd run uninterrupted?) during the day and have Radio MakeFest just broadcast them in a loop.

**Comment by MethodDan** [comment]
Hello chaps, I'm snowed under at the minute and I start a new job on Monday. If you're happy for me to just provide mp3s you can use then that's cool. On the day I'm doing workshops as you say but also running the crew with Les, fetching lunch for everyone in the van etc etc.

I can keep passing you mp3s as they are ready but doubt I can do the uploading and management of the streaming. If you're happy for me to just be an upstream contributor of audio files then I'm happy to do it.

We could also raid the Rathole Radio back catalogue for mp3's to get us going. I'm not sure how much we'll produce on the day of Makefest. Depends who turns up.

**Comment by DefProc** [comment]
Just broadcasting from any available MP3 player should work surely?

Does it need a mount or hole for an external antenna on the top of the chimney piece?

**Comment by DefProc** [comment]
@cheapjack @epsaul what hole or connection or antenna mount should be added to the chimney piece?

**Comment by epsaul** [comment]
@DefProc It would need a dipole of the size usually found on a car or FM radio. You could make one out of some coax cable and a metal coat-hanger. Or maybe a ferrite toroid balun to reduce size. I'll sort something out that's small and concealable.

**Comment by DefProc** [comment]
What if we printed a hollow tower printed in a smaller scale in black to give the impression of the 10m mast on the top of the actual RCT (76mm high on the model)?

**Comment by epsaul** [comment]
I can probably do it with an antenna 3" long of (say) 5mm diameter.

**Comment by DefProc** [comment]
We have an FM transmitter that will fit in the chimney spire (tunecast II) that will need a stereo audio input in the base of the tower, or will need 12V power, and something inside the base to broadcast.

(Added: e75c71d )

**Comment by amcewen** [comment]
So, @MethodDan, would a Dropbox folder work for you to drop mp3s into?  I'm aiming to get the BeaconBot to pull things down from Dropbox, and then play them on a loop.

Is there any chance you could record a "This is Radio MakeFest" ident for us?  Then I can get it played in between each mp3 :-)

**Comment by MethodDan** [comment]
Yeah I think that should work. It's easy enough to drop things into a dropbox folder. I have a feeling we might be challenged for bandwidth with that many geeks in one place but dropbox will just upload as soon as it can.

As for the ident thing, I can record something tonight. I'll use my best movie announcer voice. "This summer, comes the story of a Makefest...." :D

**Comment by amcewen** [comment]
We have a script to do this now - checked in at https://github.com/brett-lempereur/beaconbot/commit/fa7d581c0d480077c46478e33b51fd30baaf5b3e.  @MethodDan, I'll share a dropbox folder with you to put the mp3s into, and if you manage to get an ident, we can configure the script to play it between tracks (the script does it, but only if there's an mp3 provided)

**Comment by MethodDan** [comment]
OK sounds cool, I'll get an ident done but it might be tomorrow night now. If I give you the mp3 tomorrow night, hopefully that's early enough to load it on for Saturday :)

**Comment by amcewen** [comment]
That's fine.  Just stick it in the Dropbox folder and tell me the filename.  It'll be a two minute job to enable it.  Thanks!

**Comment by brett-lempereur** [comment]
I've got this running on the Pi that's hosting the bot now, it's pulling the files down from Dropbox every hour and playing the audio okay, everything launching at boot.

**Comment by DefProc** [comment]
Although there's a mount for audio input at the base of the tower, I'd recommend that we actually place the FM transmitter outside the tower for this install.

**Comment by amcewen** [comment]
@MethodDan suggested that RSS would work better, so have that up and running now.  It checks for new mp3s every 20 minutes.  Just need a URL for the MakeFest RSS feed from you now...

**Comment by amcewen** [comment]
URL and ident received, and deployed.
